\piecePartSpecs #`((dessus #:tag-notes dessus)
                   (haute-contre)
                   (taille)
                   (basse #:score-template "score-basse-continue")
                   (silence #:score "score-silence"))
