\piecePartSpecs #`((dessus #:score "score-violons" #:instrument "Violons")
                   (haute-contre #:score "score-violons")
                   (taille #:score "score-violons")
                   (basse #:score-template "score-basse-continue-voix")
                   (silence #:score "score-silence"))
