\piecePartSpecs #`((violon1 #:instrument "Hautbois seul")
                   (violon2 #:instrument "Hautbois seul")
                   (hautbois1 #:instrument "Hautbois seul")
                   (hautbois2 #:instrument "Hautbois seul")
                   (flute1 #:instrument "Hautbois seul")
                   (flute2 #:instrument "Hautbois seul")
                   (voix)
                   (basse #:score-template "score-basse-continue"))
