\piecePartSpecs #`((violon1 #:notes "violon")
                   (violon2 #:notes "violon")
                   (hautbois1 #:notes "flute" #:tag-notes flute1 #:instrument "Flûtes")
                   (hautbois2 #:notes "flute" #:tag-notes flute2 #:instrument "Flûtes")
                   (flute1 #:notes "flute")
                   (flute2 #:notes "flute")
                   (haute-contre)
                   (taille)
                   (basse)
                   (silence #:tag-global silence))
