\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1)
                   (hautbois2)
                   (parties)
                   (basse)
                   (basson1)
                   (basson2))
