\piecePartSpecs #`((dessus #:score "score-dessus")
                   (haute-contre #:tag-notes haute-contre)
                   (taille)
                   (quinte)
                   (basse #:tag-notes basse)
                   (basse-continue #:tag-notes basse-continue)
                   (silence #:tag-global silence))
