\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (hautbois2 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (flute1 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (flute2 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (haute-contre #:notes "haute-contre-taille")
                   (taille #:notes "haute-contre-taille")
                   (basson #:instrument "Basson" #:music ,#{ s1*16 \pageBreak #})
                   (basse #:score-template "score-basse-continue")
                   (voix))
