la, la, la, la, la, la, la, la, la, la, la, la, 
la, la, la, la, la, la, la, la, la, la, la, la, 
la, la, la, la, la, la, 
en ca -- den -- ce s'il vous plaist,
la, la, la, la, 
la jam -- be droi -- te,
la, la, la, 
ne re -- muez point tant les e -- pau -- les,
la, la, la, la, la, la, la, la, la, la,
vos deux bras sont es -- tro -- piez,
la, la, la, la, la,
haus -- sez la tes -- te,
tour -- nez la poin -- te du pied en de -- hors,
la, la, la,
dres -- sez vos -- tre corps.