\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1)
                   (hautbois2)
                   (flute1)
                   (flute2)
                   (trompette1)
                   (trompette2)
                   (timbales)
                   (basse #:instrument ,(markup #:center-column ("Bassons" "Basses"))))
