\piecePartSpecs #`((dessus #:instrument "Violons")
                   (violon1)
                   (violon2)
                   (silence #:tag-global without-marks)
                   (basse #:score-template "score-basse-continue")
                   (voix))
