\piecePartSpecs #`((violon1 #:notes "violon")
                   (violon2 #:notes "violon")
                   (hautbois1 #:notes "flute" #:instrument "Petites flûtes")
                   (hautbois2 #:notes "flute" #:instrument "Petites flûtes")
                   (flute1 #:notes "flute" #:instrument "Petites flûtes")
                   (flute2 #:notes "flute" #:instrument "Petites flûtes"))
