\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1)
                   (hautbois2)
                   (flute1)
                   (flute2)
                   (cor1)
                   (cor2)
                   (haute-contre)
                   (taille)
                   (basse)
                   (silence #:tag-global without-marks))
