\piecePartSpecs #`((dessus #:score "score-dessus")
                   (parties)
                   (basson #:instrument "Bassons")
                   (basse #:score-template "score-basse-continue")
                   (silence #:on-the-fly-markup , #{ \markup\tacet #104 #}))
