\piecePartSpecs #`((dessus)
                   (parties)
                   (basse)
                   (basse-continue #:score "score-basse-continue")
                   (silence #:score "score-silence"))
