\piecePartSpecs
#`((corno1 #:tag-global () #:instrument "Corno I en si♭")
   (corno2 #:tag-global () #:instrument "Corno II en si♭")
   (flauto1)
   (flauto2)
   (oboe1)
   (oboe2)
   (fagotto1 #:notes "fagotti" #:clef "tenor")
   (fagotto2 #:notes "fagotti" #:clef "tenor")
   (violino1 #:notes "violino1")
   (violino2 #:notes "violino2")
   (alto)
   (basso #:instrument "Basso")
   (silence #:on-the-fly-markup , #{ \markup\tacet#78 #}))
