\piecePartSpecs #`((dessus #:score "score-dessus")
                   (haute-contre)
                   (taille)
                   (basse)
                   (basse-continue #:score "score-basse-continue")
                   (silence #:score "score-silence"))
