\piecePartSpecs #`((violons #:score "score-violons")
                   (flute #:notes "silence" #:score "score-silence")
                   (hautbois #:notes "silence" #:score "score-silence")
                   (basson #:notes "basson")
                   (basse #:score "score-basse")
                   (basse-continue #:score "score-basse")
                   (silence #:score "score-silence" #:tag-global silence))
