\piecePartSpecs #`((dessus)
                   (haute-contre)
                   (taille)
                   (basse)
                   (basse-continue #:score-template "score-basse-continue-voix")
                   (silence #:score "score-silence"))