\piecePartSpecs #`((violon #:notes "violon")
                   (haute-contre)
                   (taille)
                   (voix #:instrument ,(markup #:character "Thésée"))
                   (basse)
                   (basse-continue))
