\piecePartSpecs #`((violons #:notes "violon")
                   (haute-contre)
                   (taille)
                   (basse)
                   (basse-continue)
                   (silence #:score "score-silence"))
