\piecePartSpecs #`((violino1)
                   (violino2)
                   (viola)
                   (vocal)
                   (choir)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi #:score-template "score")
                   (silence #:score "score-silence"))