\piecePartSpecs #`((violino1 #:notes "violini" #:tag-notes violino1)
                   (violino2 #:notes "violini" #:tag-notes violino2)
                   (vocal)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi #:score-template "score")
                   (silence #:score "score-silence"))
