\piecePartSpecs #`((basse-continue #:score-template "score" #:tag-global ())
                   (timbales #:tag-global ())
                   (trompette #:tag-global ())
                   (basse #:tag-global ())
                   (quinte #:tag-global violons)
                   (taille #:tag-global violons)
                   (haute-contre #:tag-global violons)
                   (dessus2 #:tag-global violons)
                   (dessus1 #:tag-global violons)
                   (silence #:tag-global ()))
