\piecePartSpecs #`((violon1)
                   (violon2)
                   (haute-contre #:notes "parties" #:tag-notes haute-contre)
                   (taille #:notes "parties" #:tag-notes taille)
                   (basson #:notes "basse" #:instrument "Basses")
                   (basse #:score "score-basse")
                   (voix #:score "score-voix")
                   (basse-continue #:score "score-basse"))
