\piecePartSpecs #`((dessus #:tag-notes violons)
                   (haute-contre #:notes "parties" #:tag-notes haute-contre)
                   (taille #:notes "parties" #:tag-notes taille)
                   (basson #:notes "basse" #:instrument "Basses")
                   (basse #:score "score-basse")
                   (basse-continue #:score "score-basse")
                   (silence #:score "score-silence"))
