\piecePartSpecs #`((dessus #:score "score-dessus")
                   (parties)
                   (basson #:clef "tenor" #:instrument "Bassons" #:notes "basson")
                   (basse)
                   (silence #:on-the-fly-markup , #{ \markup\tacet #24 #}))
