\piecePartSpecs #`((dessus #:score "score-violons")
                   (parties #:score-template "score-parties")
                   (basse)
                   (basse-continue)
                   (silence #:score "score-silence" #:tag-global silence))
