\piecePartSpecs #`((dessus1)
                   (dessus2)
                   (haute-contre)
                   (taille)
                   (voix #:score "score-voix")
                   (basson #:notes "basse" #:instrument "Basses" #:tag-notes basse)
                   (basse #:score "score-basse"))
