\piecePartSpecs #`((dessus #:score "score-dessus")
                   (haute-contre)
                   (taille)
                   (basson #:notes "basse" #:instrument "Basses" #:tag-notes basse)
                   (basse #:score "score-basse")
                   (silence #:score "score-silence"))
