\piecePartSpecs #`((dessus1 #:notes "violon1")
                   (dessus2 #:notes "violon2")
                   (haute-contre)
                   (taille)
                   (voix)
                   (basson #:notes "basse" #:instrument "Basses")
                   (basse #:score "score-basse"))
