\piecePartSpecs #`((dessus #:tag-notes dessus)
                   (haute-contre #:notes "parties" #:tag-notes haute-contre)
                   (taille #:notes "parties" #:tag-notes taille)
                   (basse #:score-template "score-basse-continue-voix")
                   (silence #:score "score-silence"))
