\piecePartSpecs #`((violino1)
                   (violino2)
                   (tromba1)
                   (tromba2)
                   (oboe1 #:notes "oboe")
                   (oboe2 #:notes "oboe")
                   (viola)
                   (vocal)
                   (choir)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi #:clef "tenor")
                   (silence #:score "score-silence"))
