\piecePartSpecs #`((violino1)
                   (violino2)
                   (tromba1)
                   (tromba2)
                   (oboe1 #:notes "oboe")
                   (oboe2 #:notes "oboe")
                   (viola)
                   (vocal)
                   (bassi #:clef "tenor"))