\piecePartSpecs #`((hautbois #:notes "hautbois" #:instrument "Hautbois")
                   (haute-contre #:notes "haute-contre-taille")
                   (taille #:notes "haute-contre-taille")
                   (basson #:notes "basson" #:clef "tenor")
                   (basse))
