\piecePartSpecs #`((violon1 #:notes "violon")
                   (violon2 #:notes "violon")
                   (hautbois1 #:notes "hautbois")
                   (hautbois2 #:notes "hautbois")
                   (flute1 #:notes "hautbois" #:instrument "Hautbois" #:tag-notes hautbois1)
                   (flute2 #:notes "hautbois" #:instrument "Hautbois" #:tag-notes hautbois2)
                   (trompette #:notes "trompette")
                   (haute-contre)
                   (taille)
                   (timbales #:notes "timbales")
                   (basson #:instrument "Basson")
                   (basse))
