\piecePartSpecs #`((violon1)
                   (violon2)
                   (flute #:notes "flutes")
                   (voix)
                   (basse #:instrument "Basse continue")
                   (basse-continue))
