\piecePartSpecs #`((violon1 #:notes "violon1")
                   (violon2 #:notes "violon2")
                   (flute #:notes "flutes")
                   (voix)
                   (basse #:instrument ,(markup #:center-column ("Basse" "continue")))
                   (basse-continue))
