\piecePartSpecs #`((violon1 #:notes "violon")
                   (violon2 #:notes "violon")
                   (hautbois1 #:notes "violon" #:instrument "Violons")
                   (hautbois2 #:notes "violon" #:instrument "Violons")
                   (flute1 #:notes "violon" #:instrument "Violons")
                   (flute2 #:notes "violon" #:instrument "Violons")
                   (voix)
                   (basse #:score-template "score-basse-continue"))
