\piecePartSpecs #`((dessus)
                   (haute-contre)
                   (taille)
                   (basse)
                   (timbales)
                   (silence #:score "score-silence"))
