\piecePartSpecs #`((dessus #:score "score-dessus")
                   (haute-contre-sol2)
                   (parties #:score-template "score-parties")
                   (basse #:score "score-basses")
                   (basse-continue))
