\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1 #:music ,#{ s2.*34 \noBreak #})
                   (hautbois2)
                   (flute1)
                   (flute2)
                   (haute-contre)
                   (taille)
                   (basse #:score-template "score-basse-continue")
                   (voix))
