\piecePartSpecs #`((hautbois1 #:tag-global autres)
                   (hautbois2 #:tag-global autres)
                   (violon1 #:tag-global autres)
                   (violon2 #:tag-global autres)
                   (haute-contre)
                   (taille)
                   (cor #:tag-global cor)
                   (basse #:instrument ,(markup #:center-column ("Bassons" "Basses")))
                   (basse-continue #:instrument ,(markup #:center-column ("Bassons" "Basses"))))