\piecePartSpecs #`((hautbois #:notes "dessus" #:tag-global autres)
                   (violon #:notes "dessus" #:tag-global autres)
                   (haute-contre #:tag-global autres)
                   (taille #:tag-global autres)
                   (cor #:tag-global cor)
                   (basson #:notes "basse")
                   (basse))
