\piecePartSpecs #`((violon1)
                   (violon2)
                   (flute)
                   (haute-contre)
                   (taille)
                   (basse #:instrument "Basse continue")
                   (voix)
                   (basse-continue #:score "score-basse-continue"))
