\piecePartSpecs #`((violon1 #:notes "violon1")
                   (violon2 #:notes "violon2")
                   (flute1 #:notes "flute")
                   (flute2 #:notes "flute")
                   (haute-contre)
                   (taille)
                   (basse)
                   (voix)
                   (basse-continue #:score "score-basse-continue"))
