\piecePartSpecs #`((dessus #:indent 0)
                   (parties #:indent 0)
                   (haute-contre-sol2 #:notes "parties" #:indent 0)
                   (basse #:indent 0)
                   (silence #:score "score-silence"))
