\piecePartSpecs
#`((tromba1)
   (tromba2)
   (corno1)
   (corno2)
   (flauto1)
   (flauto2)
   (oboe1)
   (oboe2)
   (fagotto1)
   (fagotto2)
   (violino1)
   (violino2)
   (alto)
   (basso #:instrument , #{ \markup\center-column { Basso C.b. } #})
   (timpani)
   (silence #:on-the-fly-markup , #{ \markup\tacet#82 #}))
