\piecePartSpecs #`((violon1 #:notes "violon1")
                   (violon2 #:notes "violon2")
                   (hautbois1 #:notes "hautbois1")
                   (hautbois2 #:notes "hautbois2")
                   (flute1 #:notes "flute1")
                   (flute2 #:notes "flute2")
                   (haute-contre)
                   (taille)
                   (basse #:score "score-basse")
                   (basse-continue #:score "score-basse"))
