\piecePartSpecs #`((basse-continue #:score-template "score")
                   (basse)
                   (quinte)
                   (taille)
                   (haute-contre)
                   (dessus2 #:notes "dessus2")
                   (dessus1 #:notes "dessus1"))
