\piecePartSpecs #`(,@(if (eqv? 'v1735 (ly:get-option 'indes-version))
                         `((dessus #:tag-notes conducteur #:instrument "Violons")
                           (haute-contre-sol2 #:notes "parties")
                           (parties))
                         '())
                     (basse)
                     (basse-continue #:score-template "score-basse-continue")
                     (silence #:score "score-silence"))
