\piecePartSpecs #`((violon1)
                   (violon2)
                   (flute1)
                   (flute2)
                   (hautbois1)
                   (hautbois2)
                   (haute-contre #:notes "haute-contre")
                   (taille #:notes "taille")
                   (basse #:score-template "score-basse-continue")
                   (voix))
