\piecePartSpecs #`((violino1 #:music ,#{ \clef treble \grace s8 #})
                   (violino2 #:music ,#{ \clef treble \grace s8 #})
                   (oboe1 #:notes "oboe" #:music ,#{ \clef treble \grace s8 #})
                   (oboe2 #:notes "oboe" #:music ,#{ \clef treble \grace s8 #})
                   (viola #:music ,#{ \clef alto \grace s8 #})
                   (vocal)
                   (bassi #:music ,#{ \clef bass \grace s8 #}))