\piecePartSpecs #`((dessus #:tag-notes conducteur)
                   (haute-contre #:notes "parties" #:tag-notes haute-contre)
                   (taille #:notes "parties" #:tag-notes taille)
                   (basse #:score-template "score-basse-continue")
                   (silence #:score "score-silence"))
