\piecePartSpecs #`((violon1)
                   (violon2)
                   (flute1)
                   (flute2)
                   (hautbois1 #:tag-notes violon1 #:instrument "Violons")
                   (hautbois2 #:tag-notes violon2 #:instrument "Violons")
                   (haute-contre #:notes "haute-contre")
                   (taille #:notes "taille")
                   (basse))
