\piecePartSpecs #`((violon1)
                   (violon2)
                   (flute1)
                   (flute2)
                   (hautbois1)
                   (hautbois2)
                   (haute-contre #:notes "haute-contre-taille")
                   (taille #:notes "haute-contre-taille")
                   (basse)
                   (voix))
