\piecePartSpecs #`((dessus #:score "score-dessus")
                   (violons #:tag-notes violon #:instrument "Violons")
                   (hautbois #:score "score-hautbois")
                   (haute-contre)
                   (taille)
                   (basson #:instrument "Basson" #:notes "basson")
                   (basse #:score "score-basse"))
