\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1)
                   (hautbois2)
                   (trompette)
                   (flute1)
                   (flute2)
                   (timbales #:notes "timbales")
                   (voix)
                   (basse #:score "score-basse"))
