\piecePartSpecs #`((dessus #:instrument "Violons" #:tag-notes dessus)
                   (parties)
                   (haute-contre-sol2 #:notes "parties")
                   (basse)
                   (silence #:score "score-silence"))
