\piecePartSpecs #`((violon1 #:notes "violon")
                   (violon2 #:notes "violon")
                   (hautbois1 #:notes "hautbois")
                   (hautbois2 #:notes "hautbois")
                   (flute1 #:notes "hautbois" #:tag-notes hautbois1 #:instrument "Hautbois")
                   (flute2 #:notes "hautbois" #:tag-notes hautbois2 #:instrument "Hautbois")
                   (voix)
                   (basse #:score "score-basse"))
