\piecePartSpecs #`((dessus #:score "score-dessus")
                   (trompette #:notes "trompette-hautbois")
                   (haute-contre #:notes "parties" #:tag-notes haute-contre)
                   (taille #:notes "parties" #:tag-notes taille)
                   (timbales)
                   (basse))
