%%% -*- Mode: scheme -*-
#(*all-part-specs*
  `((reduction "Reduction" ()
               ;; defaults
               (#:score "score-reduction" #:tag-global partBoth)
               ;; piece specs
               (BAAcoro)
               (BABcesare)
               (BACrecit #:score "score")
               (BBArecit #:score "score")
               (BCArecit #:score "score")
               (BCBcesare)
               (BDArecit #:score "score")
               (BDBcornelia)
               (BDCrecit #:score "score")
               (BDDsesto)
               (BEArecit #:score "score")
               (BEBcleopatra)
               (BFArecit #:score "score")
               (BFBtolomeo)
               (BGAcesare)
               (BGBrecit #:score "score")
               (BGCcesare)
               (BGDrecit #:score "score")
               (BGEcleopatra)
               (BGFrecit #:score "score")
               (BHAcornelia)
               (BHBrecit #:score "score")
               (BHCsesto)
               (BHDrecit #:score "score")
               (BHEcleopatra)
               (BIArecit #:score "score")
               (BIBcesare)
               (BJArecit #:score "score")
               (BKArecit #:score "score")
               (BKBachilla)
               (BKCrecit #:score "score")
               (BKDcorneliaSesto)

               (CAArecit #:score "score")
               (CBArecit #:score "score")
               (CBBsinfonia)
               (CBCrecit #:score "score")
               (CBErecit #:score "score")
               (CBFcleopatra)
               (CBGrecit #:score "score")
               (CBHrecit #:score "score")
               (CBIcesare)
               (CCAcornelia #:score "score")
               (CCBrecit #:score "score")
               (CDArecit #:score "score")
               (CDBachilla)
               (CDCrecit #:score "score")
               (CDDtolomeo)
               (CEArecit #:score "score")
               (CFArecit #:score "score")
               (CFBcornelia)
               (CFCrecit #:score "score")
               (CFDsesto)
               (CGArecit #:score "score")
               (CGBcleopatra)
               (CGCrecit #:score "score")
               (CHArecit #:score "score")
               (CHBcesare)
               (CHCrecit)
               (CHDcleopatra)
               (CIAtolomeo)
               (CIBrecit #:score "score")
               (CJArecit #:score "score")
               (CKArecit #:score "score")
               (CKBsesto)
               )))