\piecePartSpecs #`((hautbois1 #:tag-global autres)
                   (hautbois2 #:tag-global autres)
                   (violon1 #:tag-global autres)
                   (violon2 #:tag-global autres)
                   (haute-contre)
                   (taille)
                   (cor #:tag-global cor)
                   (basson #:tag-global autres #:notes "basse")
                   (basse #:tag-global autres)
                   (voix))
