\piecePartSpecs #`((violino1)
                   (violino2)
                   (viola)
                   (vocal #:indent 0)
                   (choir #:indent 0)
                   (vocal-keyboard #:indent 0)
                   (keyboard #:indent 0)
                   (bassi)
                   (silence #:score "score-silence"))