\piecePartSpecs #`((dessus #:score "score-dessus")
                   (parties #:indent 0)
                   (basse #:score "score-basse")
                   (basse-continue #:score-template "score-basse-continue")
                   (silence #:score "score-silence"))
