\includeNotes "dessus-a"
s4*0^"Violons" \includeNotes "dessus-b"
s4*0^"Hautbois" \includeNotes "dessus-c1"
s4*0^"Violons" \includeNotes "dessus-d"
s4*0^"Hautbois" \includeNotes "dessus-e1"
s4*0^"Violons" \includeNotes "dessus-f"