\piecePartSpecs #`((dessus)
                   (parties #:score-template "score-parties")
                   (haute-contre-sol2)
                   (basse #:score "score-basse")
                   (basse-continue))
