\piecePartSpecs #(let ((instr-musette (markup #:center-column ("Deux" "musettes"))))
                   `((violon1 #:notes "violon1")
                     (violon2 #:notes "violon2")
                     (hautbois1 #:notes "musette" #:instrument ,instr-musette)
                     (hautbois2 #:notes "musette" #:instrument ,instr-musette)
                     (flute1 #:notes "musette" #:instrument ,instr-musette)
                     (flute2 #:notes "musette" #:instrument ,instr-musette)
                     (musette1)
                     (musette2)
                     (parties)
                     (basse #:score-template "score-basse-continue-voix")
                     (voix)))
