%%% -*- Mode: scheme -*-
#(*all-part-specs*
  `((dessus1 "Dessus I" ()
             ;; default note-filename, default score file
             "dessus" "score"
             ;; piece specs
             (AAAouverture)
             (AACchoeur)
             (AADritournelle)
             (AAFmenuet)
             (AAIritournelle)
             
             (BAAritournelle #:notes "dessus1")
             (BBBritournelle #:notes "dessus1")
             (BBCaffliges #:notes "dessus1")
             (BBDritournelle #:music ,#{ s1.*4\break #})
             (BBFritournelle)

             (CAAsymphonie)
             (CBBair)
             (CBCvulcain)
             (CBDritournelle)
             (CCAritournelle #:notes "dessus1")
             (CCCritournelle)
             (CEAritournelle #:notes "dessus1")
             (CFAritournelle #:notes "dessus1")
             (CFCritournelle #:notes "dessus1")
             (CFEair)
             
             (DAAritournelle #:notes "dessus1")
             (DBApsyche #:notes "dessus1")
             (DEBritournelle #:notes "dessus1")

             (EAAritournelle #:notes "dessus1")
             (EADair)
             (EAHair)
             (EAIair)
             
             (FAAritournelle #:notes "dessus1")
             (FDAprelude)
             (FDDritournelle)
             (FDFchoeur)
             (FDGritournelle)
             (FDImome #:notes "dessus1")
             (FDKchoeur)
             (FDLritournelle)
             (FDNritournelle)
             (FDPair)
             (FDRair)
             (FDUentree)
             (FDVmome #:notes "dessus1")
             (FDXprelude #:tag violons)
             (FDYrondeau)
             (FDZair))
    (dessus2 "Dessus II" ()
             ;; default note-filename, piece specs
             "dessus" "score"
             (AAAouverture)
             (AACchoeur)
             (AADritournelle)
             (AAFmenuet)
             (AAIritournelle)
             
             (BAAritournelle #:notes "dessus2")
             (BBBritournelle #:notes "dessus2")
             (BBCaffliges #:notes "dessus2")
             (BBDritournelle #:music ,#{ s1.*4\break #})
             (BBFritournelle)

             (CAAsymphonie)
             (CBBair)
             (CBCvulcain)
             (CBDritournelle)
             (CCAritournelle #:notes "dessus2")
             (CCCritournelle)
             (CEAritournelle #:notes "dessus2")
             (CFAritournelle #:notes "dessus2")
             (CFCritournelle #:notes "dessus2")
             (CFEair)
             
             (DAAritournelle #:notes "dessus2")
             (DBApsyche #:notes "dessus2")
             (DEBritournelle #:notes "dessus2")

             (EAAritournelle #:notes "dessus2")
             (EADair)
             (EAHair)
             (EAIair)
             
             (FAAritournelle #:notes "dessus2")
             (FDAprelude)
             (FDDritournelle)
             (FDFchoeur)
             (FDGritournelle)
             (FDImome #:notes "dessus2")
             (FDKchoeur)
             (FDLritournelle)
             (FDNritournelle)
             (FDPair)
             (FDRair)
             (FDUentree)
             (FDVmome #:notes "dessus2")
             (FDXprelude #:tag violons)
             (FDYrondeau)
             (FDZair))
    (haute-contre "Haute-contre de violon" ()
             ;; default note-filename, piece specs
             "haute-contre" "score"
             (AAAouverture)
             (AACchoeur)
             (AADritournelle)
             (AAFmenuet)
             (AAIritournelle)
             
             (BBBritournelle)
             (BBFritournelle)

             (CAAsymphonie)
             (CBBair)
             (CBCvulcain)
             (CBDritournelle)
             (CCCritournelle)
             (CFEair)
             
             (EADair)
             (EAHair)
             (EAIair)
             
             (FDAprelude)
             (FDDritournelle)
             (FDFchoeur #:music ,#{ s1*22 s2.*11 \pageBreak #})
             (FDGritournelle)
             (FDKchoeur)
             (FDLritournelle)
             (FDNritournelle)
             (FDPair)
             (FDRair)
             (FDUentree)
             (FDXprelude #:tag violons)
             (FDYrondeau)
             (FDZair))
    (taille "Taille de violon" ()
             ;; default note-filename, piece specs
             "taille" "score-alto"
             (AAAouverture)
             (AACchoeur)
             (AADritournelle)
             (AAFmenuet)
             (AAIritournelle)
             
             (BBBritournelle)
             (BBFritournelle
              #:music ,#{ \repeat unfold 10 {s1\noBreak} s1 \break
                          \repeat unfold 11 {s1\noBreak} s1 \break
                          \repeat unfold 10 {s1\noBreak} 
                          #})

             (CAAsymphonie)
             (CBBair)
             (CBCvulcain)
             (CBDritournelle)
             (CCCritournelle)
             (CFEair)
             
             (EADair)
             (EAHair)
             (EAIair)
             
             (FDAprelude)
             (FDDritournelle)
             (FDFchoeur #:music ,#{ s1*22 s2.*11 \pageBreak #})
             (FDGritournelle)
             (FDKchoeur)
             (FDLritournelle)
             (FDNritournelle)
             (FDPair)
             (FDRair)
             (FDUentree)
             (FDXprelude #:tag violons)
             (FDYrondeau)
             (FDZair))
    (quinte "Quinte de violon" ()
             ;; default note-filename, piece specs
             "quinte" "score-alto"
             (AAAouverture)
             (AACchoeur)
             (AADritournelle)
             (AAFmenuet)
             (AAIritournelle)
             
             (BBBritournelle)
             (BBFritournelle)

             (CAAsymphonie)
             (CBBair)
             (CBCvulcain)
             (CBDritournelle)
             (CCCritournelle)
             (CFEair)
             
             (EADair)
             (EAHair)
             (EAIair)
             
             (FDAprelude)
             (FDDritournelle)
             (FDFchoeur #:music ,#{ s1*22 s2.*40 \pageBreak #})
             (FDGritournelle)
             (FDKchoeur)
             (FDLritournelle)
             (FDNritournelle)
             (FDPair)
             (FDRair)
             (FDUentree)
             (FDXprelude #:tag violons)
             (FDYrondeau)
             (FDZair))
    (basse "Basse" ()
           "basse" "score-basse"
           (AAAouverture)
           (AACchoeur)
           (AADritournelle)
           (AAFmenuet)
           (AAIritournelle)

           (BAAritournelle)
           (BBBritournelle)
           (BBFritournelle)

           (CAAsymphonie)
           (CBBair)
           (CBDritournelle)
           (CCAritournelle)
           (CCCritournelle)
           (CEAritournelle)
           (CFAritournelle)
           (CFCritournelle)
           (CFEair)

           (DAAritournelle)
           (DEBritournelle)

           (EAAritournelle #:notes "basse2")
           (EADair)
           (EAHair)
           (EAIair)

           (FAAritournelle)
           (FDAprelude)
           (FDDritournelle)
           (FDFchoeur)
           (FDGritournelle)
           (FDKchoeur)
           (FDLritournelle)
           (FDNritournelle)
           (FDPair)
           (FDRair)
           (FDUentree)
           (FDXprelude)
           (FDYrondeau)
           (FDZair))
    ))