\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1)
                   (hautbois2)
                   (flute1 #:instrument ,(markup #:center-column ("Hautbois" "Violons")))
                   (flute2 #:instrument ,(markup #:center-column ("Hautbois" "Violons")))
                   (haute-contre)
                   (taille)
                   (basse)
                   (basson))
