\piecePartSpecs #`((dessus #:score "score-dessus")
                   (haute-contre)
                   (taille)
                   (basse)
                   (basse-continue #:score-template "score-basse-continue-voix2")
                   (silence #:score "score-silence"))