\piecePartSpecs #`((dessus)
                   (haute-contre)
                   (taille)
                   (quinte)
                   (basse #:tag-notes basse)
                   (basse-continue #:tag-notes basse-continue)
                   (choeur)
                   (silence #:score "score-silence"))
