\piecePartSpecs #`((violon1)
                   (violon2)
                   (flute1)
                   (flute2)
                   (hautbois1)
                   (hautbois2)
                   (haute-contre)
                   (taille)
                   (voix)
                   (basse #:score "score-basse"))
