\piecePartSpecs #`((dessus #:score "score-dessus")
                   (haute-contre)
                   (taille)
                   (basse #:score "score-basse")
                   (basse-continue #:score "score-basse")
                   (silence #:score "score-silence" #:tag-notes silence))
