\piecePartSpecs #`((violon1 #:notes "violon1")
                   (violon2 #:notes "violon2")
                   (flute #:notes "flute")
                   (voix #:instrument ,(markup #:smallCaps "Phèdre"))
                   (basse #:instrument "Basse continue")
                   (basse-continue))
