\piecePartSpecs #`((violons #:score "score-violons")
                   (flutes #:notes "flute" #:instrument "Flutes")
                   (basse #:instrument "B.C.")
                   (basse-continue #:score-template "score-basse-continue-voix")
                   (silence #:score "score-silence"))
