\piecePartSpecs #`((violon1 #:instrument "Hautbois" #:tag-notes hautbois1)
                   (violon2 #:instrument "Hautbois" #:tag-notes hautbois2)
                   (hautbois1)
                   (hautbois2)
                   (flute1 #:instrument "Hautbois" #:tag-notes hautbois1)
                   (flute2 #:instrument "Hautbois" #:tag-notes hautbois2)
                   (voix)
                   (basson #:notes "basson" #:clef "tenor")
                   (basse #:score-template "score-basse-continue"))
