\piecePartSpecs #`((violon1)
                   (violon2)
                   (flute1)
                   (flute2)
                   (haute-contre)
                   (taille)
                   (basse #:instrument "Basse continue")
                   (basse-continue))
