\piecePartSpecs #`((vocal)
                   (vocal-keyboard #:score "score")
                   (keyboard #:score "score-bassi")
                   (bassi #:score "score-bassi")
                   (silence #:score "score-silence"))