\piecePartSpecs #`((hautbois1 #:notes "hautbois" #:tag-global autres)
                   (hautbois2 #:notes "hautbois" #:tag-global autres)
                   (cor #:tag-global cor #:instrument "Cors en ré")
                   (basse #:notes "basson" #:tag-global autres #:instrument "Basson")
                   (basse-continue #:notes "basson" #:tag-global autres #:instrument "Basson"))
