\piecePartSpecs #`((dessus1)
                   (dessus2)
                   (haute-contre #:notes "haute-contre-taille")
                   (taille #:notes "haute-contre-taille")
                   (basse))
