\piecePartSpecs #`((dessus #:tag-global autres)
                   (haute-contre #:tag-global autres)
                   (taille #:tag-global autres)
                   (cor #:tag-global cor)
                   (basse #:tag-global autres))
