\piecePartSpecs #`((hautbois1 #:notes "hautbois1")
                   (hautbois2 #:notes "hautbois2")
                   (violon1 #:notes "hautbois1" #:instrument "Hautbois")
                   (violon2 #:notes "hautbois2" #:instrument "Hautbois")
                   (flute1  #:notes "hautbois1" #:instrument "Hautbois")
                   (flute2  #:notes "hautbois2" #:instrument "Hautbois")
                   (basse #:score "score-basse"))
