\piecePartSpecs #`((violon1 #:notes "violon")
                   (violon2 #:notes "violon")
                   (flute1 #:notes "flute")
                   (flute2 #:notes "flute")
                   (hautbois1 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (hautbois2 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (haute-contre)
                   (taille)
                   (basson)
                   (basse #:score-template "score-basse-continue")
                   (voix))
