\piecePartSpecs #`((dessus)
                   (haute-contre #:notes "haute-contre-taille")
                   (taille #:notes "haute-contre-taille")
                   (basse)
                   (silence #:score "score-silence"))
