\piecePartSpecs #`((dessus #:instrument "Violons")
                   (parties #:score-template "score-parties")
                   (basse)
                   (timbales)
                   (silence #:score "score-silence"))
