\piecePartSpecs #`((violino1)
                   (violino2)
                   (oboe1)
                   (oboe2)
                   (viola)
                   (vocal)
                   (choir)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi)
                   (silence #:score "score-silence"))
