\piecePartSpecs #`((dessus)
                   (haute-contre #:tag-notes 'haute-contre)
                   (taille #:tag-notes 'taille)
                   (voix)
                   (basson #:instrument "Basson" #:notes "basson")
                   (basse #:score "score-basse"))
