\piecePartSpecs #`((violon1 #:notes "violon")
                   (violon2 #:notes "violon")
                   (flute1 #:notes "flute")
                   (flute2 #:notes "flute")
                   (haute-contre)
                   (taille)
                   (basse)
                   (basse-continue))
