\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1)
                   (hautbois2)
                   (flute1)
                   (flute2)
                   (haute-contre)
                   (taille)
                   (basse)
                   (basse-continue))
