\piecePartSpecs #`((violon1 #:notes "violon-hautbois" #:ragged #t)
                   (violon2 #:notes "violon-hautbois" #:ragged #t)
                   (hautbois1 #:notes "violon-hautbois" #:ragged #t)
                   (hautbois2 #:notes "violon-hautbois" #:ragged #t)
                   (haute-contre #:ragged #t)
                   (taille #:ragged #t)
                   (basse #:ragged #t)
                   (basse-continue #:ragged #t))
