\piecePartSpecs #`((dessus)
                   (parties #:score-template "score-parties")
                   (dessus2-hc)
                   (basse)
                   (silence #:tag-global silence))
