\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1)
                   (hautbois2)
                   (flute1)
                   (flute2)
                   (trompette)
                   (haute-contre #:notes "haute-contre-taille" #:tag-notes ())
                   (taille #:notes "haute-contre-taille" #:tag-notes ())
                   (timbales #:notes "timbales")
                   (voix)
                   (basse #:score "score-basse"))
