\piecePartSpecs #`((flute)
                   (violon)
                   (haute-contre)
                   (taille)
                   (basse #:instrument "Basse continue")
                   (basse-continue)
                   (voix))
