\piecePartSpecs #`((dessus #:score "score-dessus")
                   (parties #:score-template "score-parties")
                   (basse #:instrument "B.C.")
                   (basse-continue #:score-template "score-basse-continue")
                   (silence #:score "score-silence"))
