\piecePartSpecs #`((violons)
                   (flutes #:tag-notes violons)
                   (hautbois #:tag-notes violons)
                   (haute-contre)
                   (taille)
                   (basse)
                   (basse-continue #:score-template "score-basse-continue-voix")
                   (silence #:score "score-silence" #:tag-global silence))
