\piecePartSpecs #`((violon)
                   (flute)
                   (hautbois #:instrument ,(markup #:center-column ("Flûtes" "Violons")))
                   (haute-contre)
                   (taille)
                   (basse))
