\piecePartSpecs #`((violons #:score "score-violons")
                   (haute-contre)
                   (taille)
                   (flutes #:score-template "score-silence" #:notes "silence" #:ragged #t)
                   (hautbois #:score-template "score-silence" #:notes "silence" #:ragged #t)
                   (basson #:notes "bassons")
                   (basse #:score "score-basse"))
