\piecePartSpecs #`((dessus)
                   (haute-contre #:notes "haute-contre")
                   (taille #:notes "taille")
                   (quinte #:notes "quinte")
                   (basse))
