\piecePartSpecs #`((dessus #:indent 0)
                   (haute-contre #:indent 0)
                   (taille #:indent 0)
                   (quinte #:indent 0)
                   (basse #:indent 0)
                   (basse-continue #:indent 0)
                   (silence #:score "score-silence" #:indent 0))
