\piecePartSpecs #`((violons #:notes "dessus" #:tag-notes violons)
                   (hautbois #:score "score-hautbois")
                   (haute-contre #:notes "parties" #:tag-notes haute-contre)
                   (taille #:notes "parties" #:tag-notes taille)
                   (basson #:notes "basson")
                   (basse #:instrument "B.C.")
                   (silence #:score "score-silence" #:tag-global silence))
