\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1)
                   (hautbois2)
                   (haute-contre)
                   (taille)
                   (basson)
                   (basse #:instrument "Basse continue")
                   (voix)
                   (basse-continue))
