\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1)
                   (hautbois2)
                   (flute1)
                   (flute2)
                   (haute-contre #:notes "haute-contre-taille" #:tag-notes haute-contre)
                   (taille #:notes "haute-contre-taille" #:tag-notes taille)
                   (voix)
                   (basse)
                   (basson))
