\piecePartSpecs #`((violon)
                   (hautbois)
                   (flute #:instrument "Petites flûtes")
                   (haute-contre #:notes "haute-contre-taille")
                   (taille #:notes "haute-contre-taille")
                   (basson)
                   (basse))
