\piecePartSpecs #`((dessus1)
                   (dessus2)
                   (hautbois1 #:notes "dessus1" #:instrument ,(markup #:center-column ("Violons" "Flûtes")))
                   (hautbois1 #:notes "dessus2" #:instrument ,(markup #:center-column ("Violons" "Flûtes")))
                   (haute-contre)
                   (taille)
                   (voix))
