\piecePartSpecs #`((violino1)
                   (violino2)
                   (viola)
                   (vocal)
                   (choir)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi #:clef "treble")
                   (silence #:score "score-silence"))