\piecePartSpecs #`((violon1)
                   (violon2)
                   (flute1)
                   (flute2)
                   (hautbois1 #:tag-notes #'flute1 #:instrument "Flûtes")
                   (hautbois2 #:tag-notes #'flute2 #:instrument "Flûtes")
                   (haute-contre)
                   (taille)
                   (basse #:instrument "Basse continue")
                   (basse-continue #:score-template "score"))
