\piecePartSpecs #`((violons #:tag-notes violons)
                   (flutes #:tag-notes flutes)
                   (haute-contre)
                   (taille)
                   (basse #:instrument "B.C.")
                   (basse-continue #:score-template "score"))
