\piecePartSpecs #`((dessus #:indent 0)
                   (haute-contre #:indent 0)
                   (taille #:indent 0)
                   (quinte #:indent 0)
                   (basse #:indent 0)
                   (voix #:score "score-voix")
                   (basse-continue #:indent 0 #:notes "basse-continue"))
