\piecePartSpecs #`((dessus)
                   (haute-contre)
                   (taille)
                   (basson #:notes "basse" #:instrument "Basses")
                   (basse #:score "score-basse"))
