\piecePartSpecs #`((dessus #:tag-notes violons #:instrument "Violons")
                   (trompette-timbales #:score "score-tt")
                   (parties)
                   (basse)
                   (silence #:score "score-silence"))
