\piecePartSpecs #`((dessus #:tag-notes violons #:instrument "Violons")
                   (trompette)
                   (parties)
                   (basse)
                   (timbales)
                   (silence #:score "score-silence"))
