\piecePartSpecs #(let ((breaks #{ s2 s1*35 s2.*21 \break #}))
                   `((dessus #:score "score-dessus")
                     (haute-contre)
                     (taille)
                     (basse #:music ,breaks)
                     (basse-continue #:music ,breaks)
                     (silence #:score "score-silence")))
