\piecePartSpecs #`((trompette #:notes "dessus" #:tag-notes dessus1)
                   (dessus #:score "score-dessus")
                   (parties)
                   (timbales #:notes "timbales")
                   (basse))
