\piecePartSpecs #`((dessus)
                   (haute-contre)
                   (taille)
                   (quinte)
                   (basse)
                   (basse-continue #:notes "basse-continue")
                   (silence #:on-the-fly-markup , #{ \markup\fontsize #2 { \hspace #10 Tacet } #}))
