\piecePartSpecs #`((dessus1 #:notes "dessus1")
                   (dessus2 #:notes "dessus2")
                   (trompette1)
                   (trompette2)
                   (timbales)
                   (haute-contre #:notes "haute-contre")
                   (taille #:notes "taille")
                   (basse))
