\piecePartSpecs #`((dessus #:tag-notes violons #:instrument "Violons")
                   (trompette)
                   (haute-contre #:notes "haute-contre-taille")
                   (taille #:notes "haute-contre-taille")
                   (basse)
                   (timbales)
                   (silence #:score "score-silence"))
