\piecePartSpecs #`((violon1 #:notes "violon")
                   (violon2 #:notes "violon")
                   (hautbois1 #:notes "hautbois")
                   (hautbois2 #:notes "hautbois")
                   (flute1 #:tag-notes hautbois1 #:notes "hautbois" #:instrument "Hautbois")
                   (flute2 #:tag-notes hautbois2 #:notes "hautbois" #:instrument "Hautbois")
                   (haute-contre)
                   (taille)
                   (basson)
                   (basse))
