\piecePartSpecs
#`((tromba1 #:instrument "Tromba I in C")
   (tromba2 #:instrument "Tromba II in C")
   (oboe1 #:notes "oboe1")
   (oboe2 #:notes "oboe2")
   (clarinetto1 #:notes "oboe1")
   (clarinetto2 #:notes "oboe2")
   (fagotto1)
   (fagotto2)
   (violino1)
   (violino2)
   (alto)
   (basso #:instrument "Basso")
   (silence #:on-the-fly-markup , #{ \markup\tacet#36 #}))
