\piecePartSpecs #`((dessus)
                   (haute-contre)
                   (taille)
                   (quinte)
                   (basse)
                   (basse-continue)
                   (silence #:score "score-silence"))
