\piecePartSpecs #`((flute)
                   (violon)
                   (haute-contre)
                   (taille)
                   (basson #:notes "basse")
                   (basse #:score "score-basse")
                   (voix))
