\piecePartSpecs #`((flute1 #:notes "flute")
                   (flute2 #:notes "flute")
                   (violon1 #:notes "violon")
                   (violon2 #:notes "violon")
                   (haute-contre)
                   (taille)
                   (basse #:score "score-basse")
                   (voix)
                   (basse-continue #:score "score-basse"))
