\piecePartSpecs
#`((tromba1 #:instrument , #{ \markup\center-column { Tromba col Corno } #})
   (tromba2 #:instrument , #{ \markup\center-column { Tromba col Corno } #})
   (oboe1)
   (oboe2)
   (fagotto1)
   (fagotto2)
   (violino1)
   (violino2)
   (alto)
   (basso #:instrument , #{ \markup\center-column { Basso Contrabasso } #})
   (silence #:on-the-fly-markup , #{ \markup\tacet#179 #}))