\piecePartSpecs #`((violon1 #:notes "violon1")
                   (violon2 #:notes "violon2")
                   (hautbois1 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (hautbois2 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (flute1 #:notes "flute")
                   (flute2 #:notes "flute"))
