\piecePartSpecs #`((violon)
                   (haute-contre)
                   (taille)
                   (basson)
                   (basse #:score "score-basse")
                   (voix)
                   (basse-continue #:score "score-basse"))
