\piecePartSpecs #`((dessus)
                   (haute-contre)
                   (taille)
                   (basson #:notes "basson")
                   (basse)
                   (silence #:tag-global silence))
