\piecePartSpecs
#`((tromba1 #:tag-global () #:instrument "Corno I in C")
   (tromba2 #:tag-global () #:instrument "Tromba II in C")
   (oboe1)
   (oboe2)
   (fagotto1)
   (fagotto2)
   (violino1)
   (violino2)
   (alto)
   (basso #:instrument "Basso")
   (silence #:on-the-fly-markup , #{ \markup\tacet#73 #}))
