\piecePartSpecs #`((dessus #:indent 0)
                   (haute-contre #:indent 0)
                   (taille #:indent 0)
                   (quinte #:indent 0)
                   (basse #:indent 0 #:tag-notes basse)
                   (basse-continue #:indent 0 #:tag-notes basse-continue)
                   (choeur)
                   (silence #:score "score-silence"))
