\piecePartSpecs #`((violon1 #:notes "violon1")
                   (violon2 #:notes "violon2")
                   (basse)
                   (voix)
                   (basse-continue #:score "score-basse-continue"))
