\piecePartSpecs #`((dessus #:score "score-dessus")
                   (trompette-timbales #:score "score-tt")
                   (parties #:score-template "score-parties2")
                   (haute-contre-sol2 #:notes "parties")
                   (basse))
