\piecePartSpecs #(let ((breaks #{ s2 s1*3 s2 s2 s1*5 s2 \break #}))
                  `((dessus #:music ,breaks)
                    (haute-contre #:music ,breaks)
                    (taille #:music ,breaks)
                    (basson #:music ,breaks)
                    (basse #:music ,breaks)))
