\piecePartSpecs #`((hautbois1 #:notes "hautbois1" #:tag-global autres)
                   (hautbois2 #:notes "hautbois2" #:tag-global autres)
                   (violon1 #:notes "violon1" #:tag-global autres)
                   (violon2 #:notes "violon2" #:tag-global autres)
                   (haute-contre #:tag-global autres)
                   (taille #:tag-global autres)
                   (cor #:tag-global cor)
                   (basse #:score "score-basse"))
