\piecePartSpecs #`((violon1 #:notes "dessus1")
                   (violon2 #:notes "dessus2")
                   (hautbois1 #:notes "dessus1")
                   (hautbois2 #:notes "dessus2")
                   (haute-contre #:notes "haute-contre-taille")
                   (taille #:notes "haute-contre-taille")
                   (basse)
                   (voix)
                   (basse-continue))
