\piecePartSpecs #(let ((breaks #{ s1*16\break s1*16\break #}))
                   `((dessus #:music ,breaks)
                     (haute-contre #:music ,breaks)
                     (taille #:music ,breaks)
                     (basse #:music ,breaks)))
