\piecePartSpecs #`((violon1 #:notes "dessus1")
                   (violon2 #:notes "dessus2")
                   (hautbois1 #:notes "dessus1")
                   (hautbois2 #:notes "dessus2")
                   (flute1 #:notes "dessus1")
                   (flute2 #:notes "dessus2")
                   (basson)
                   (basse))
