\piecePartSpecs #`((hautbois)
                   (violon1)
                   (violon2)
                   (haute-contre #:notes "parties")
                   (taille #:notes "parties")
                   (basson)
                   (basse #:instrument "Basse continue")
                   (basse-continue #:score-template "score"))
