\piecePartSpecs #`((hautbois)
                   (violon1)
                   (violon2)
                   (haute-contre #:notes "haute-contre-taille")
                   (taille #:notes "haute-contre-taille")
                   (basson)
                   (basse #:instrument "Basse continue")
                   (basse-continue))
