\piecePartSpecs #`((hautbois1 #:notes "hautbois")
                   (hautbois2 #:notes "hautbois")
                   (violon1 #:notes "violon1")
                   (violon2 #:notes "violon2")
                   (haute-contre #:notes "haute-contre-taille")
                   (taille #:notes "haute-contre-taille")
                   (basse #:score "score-basse")
                   (basse-continue #:score "score-basse"))
