\piecePartSpecs #`((dessus #:score "score-dessus")
                   (parties #:score "score-parties")
                   (basse #:score "score-basse")
                   (basse-continue #:score-template "score-basse-continue")
                   (silence #:score "score-silence"))
