\piecePartSpecs #`((violon1)
                   (violon2)
                   (flute1 #:notes "flute")
                   (flute2 #:notes "flute")
                   (haute-contre #:notes "haute-contre")
                   (taille #:notes "taille")
                   (basse)
                   (voix)
                   (silence #:tag-global without-marks))
