\piecePartSpecs #`((dessus)
                   (parties #:score-template "score-parties")
                   (dessus2-hc)
                   (basse #:score "score-basse")
                   (silence #:tag-global silence))
