\piecePartSpecs #`((violon #:notes "dessus")
                   (haute-contre)
                   (taille)
                   (basson #:notes "basse" #:instrument "Basses")
                   (basse #:score "score-basse")
                   (basse-continue #:score "score-basse"))
