\piecePartSpecs #`((dessus #:score "score-violons")
                   (parties #:score-template "score-parties")
                   (basse #:score "score-basse")
                   (basse-continue)
                   (silence #:score "score-silence"))
