\piecePartSpecs #`((violon1 #:notes "violon1")
                   (violon2 #:notes "violon2")
                   (haute-contre)
                   (taille)
                   (voix)
                   (basse #:score "score-basse")
                   (basse-continue #:score "score-basse"))
