\piecePartSpecs #`((dessus #:score "score-dessus")
                   (trompette #:notes "trompette")
                   (timbales #:notes "timbales")
                   (basse #:score-template "score-basse-continue-voix")
                   (silence #:score "score-silence"))
