\piecePartSpecs #`((trompette-timbales #:score "score-tt")
                   (dessus #:score "score-dessus")
                   (parties)
                   (haute-contre-sol2 #:notes "parties")
                   (basse))
