\piecePartSpecs #`((dessus #:score "score-dessus")
                   (haute-contre)
                   (taille)
                   (quinte)
                   (basse #:tag-notes part)
                   (basse-continue #:tag-notes part))
