\piecePartSpecs #`((dessus)
                   (haute-contre)
                   (taille)
                   (quinte #:tag-global ())
                   (basse)
                   (basse-continue)
                   (silence #:tag-global ()))
