\includeNotes "dessus-a"
\bar "dashed" s4*0^"Flûtes" \includeNotes "dessus-b2"
\bar "dashed" \includeNotes "dessus-c"
\bar "dashed" s4*0^"Flûtes" \includeNotes "dessus-d2"
\bar "dashed" \includeNotes "dessus-e"
\bar "dashed" s4*0^"Flûtes" \includeNotes "dessus-f2"
\bar "dashed" \includeNotes "dessus-g"
\bar "dashed" s4*0^"Flûtes" \includeNotes "dessus-h2"
\bar "dashed" \includeNotes "dessus-i"
