\includeNotes "dessus-a"
\bar "dashed" s4*0^"Flûtes" \includeNotes "dessus-b1"
\bar "dashed" \includeNotes "dessus-c"
\bar "dashed" s4*0^"Flûtes" \includeNotes "dessus-d1"
\bar "dashed" \includeNotes "dessus-e"
\bar "dashed" s4*0^"Flûtes" \includeNotes "dessus-f1"
\bar "dashed" \includeNotes "dessus-g"
\bar "dashed" s4*0^"Flûtes" \includeNotes "dessus-h1"
\bar "dashed" \includeNotes "dessus-i"
