\piecePartSpecs #`((dessus #:score "score-dessus")
                   (trompette-timbales #:score "score-tt")
                   (parties)
                   (basse)
                   (silence #:on-the-fly-markup , #{ \markup\tacet #14 #}))
