\piecePartSpecs #`((violon1 #:notes "dessus1")
                   (violon2 #:notes "dessus2")
                   (hautbois1 #:notes "dessus1")
                   (hautbois2 #:notes "dessus1")
                   (flute1 #:notes "dessus1")
                   (flute2 #:notes "dessus1")
                   (haute-contre)
                   (taille)
                   (basse)
                   (basse-continue))
