\piecePartSpecs #`((dessus #:notes "dessus1")
                   (violon2 #:notes "dessus2")
                   (haute-contre)
                   (taille)
                   (basse)
                   (basson #:notes "basse"))
