\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois)
                   (haute-contre)
                   (taille)
                   (basse)
                   (basson))
