\piecePartSpecs #`((violon1)
                   (violon2)
                   (haute-contre)
                   (taille)
                   (basse)
                   (voix)
                   (basse-continue #:score "score-basse-continue"))
