\includeNotes "dessus-a"
s4*0^"Flûtes" \includeNotes "dessus-b1"
s4*0^"Violons" \includeNotes "dessus-c"
s4*0^"Flûtes" \includeNotes "dessus-d1"
s4*0^"Violons" \includeNotes "dessus-e"
s4*0^"Flûtes" \includeNotes "dessus-f1"
s4*0^"Violons" \includeNotes "dessus-g"
s4*0^"Flûtes" \includeNotes "dessus-h1"
s4*0^"Violons" \includeNotes "dessus-i"
