\includeNotes "dessus-a"
s4*0^"Flûtes" \includeNotes "dessus-b2"
s4*0^"Violons" \includeNotes "dessus-c"
s4*0^"Flûtes" \includeNotes "dessus-d2"
s4*0^"Violons" \includeNotes "dessus-e"
s4*0^"Flûtes" \includeNotes "dessus-f2"
s4*0^"Violons" \includeNotes "dessus-g"
s4*0^"Flûtes" \includeNotes "dessus-h2"
s4*0^"Violons" \includeNotes "dessus-i"
