\piecePartSpecs #`((dessus1 #:notes "dessus1")
                   (dessus2 #:notes "dessus2")
                   (haute-contre)
                   (taille #:notes "taille-part")
                   (quinte)
                   (basse)
                   (basse-continue))
