\piecePartSpecs #`((dessus)
                   (haute-contre)
                   (taille #:notes "taille-part")
                   (quinte)
                   (basse)
                   (basse-continue))
