\includeNotes "taille-a"
s4*0^"Flûtes" \includeNotes "taille-b"
s4*0^"Violons" \includeNotes "taille-c"
s4*0^"Flûtes" \includeNotes "taille-d"
s4*0^"Violons" \includeNotes "taille-e"
s4*0^"Flûtes" \includeNotes "taille-f"
s4*0^"Violons" \includeNotes "taille-g"
s4*0^"Flûtes" \includeNotes "taille-h"
s4*0^"Violons" \includeNotes "taille-i"
