\piecePartSpecs #(let ((breaks #{ s2 s1*7 s2 \break s2 s1*7 s2 \break #})
                       (breaks2 #{ s2 s1*7 s2 \break #}))
                   `((violon1 #:music ,breaks)
                     (violon2 #:music ,breaks)
                     (hautbois1 #:music ,breaks #:tag-notes flute1 #:instrument "Flûtes")
                     (hautbois2 #:music ,breaks #:tag-notes flute2 #:instrument "Flûtes")
                     (flute1 #:music ,breaks)
                     (flute2 #:music ,breaks)
                     (haute-contre #:music ,breaks2)
                     (taille #:music ,breaks2)
                     (basse #:music)))
