\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1 #:tag-notes flute1 #:instrument "Flûtes")
                   (hautbois2 #:tag-notes flute2 #:instrument "Flûtes")
                   (flute1)
                   (flute2)
                   (haute-contre)
                   (taille)
                   (basse))
