\piecePartSpecs #`((dessus1)
                   (dessus2)
                   (haute-contre)
                   (taille)
                   (quinte)
                   (basse)
                   (voix #:global-tag ())
                   (basse-continue #:tag-global ())
                   (silence #:tag-global ()))
