\piecePartSpecs #`((violon1 #:notes "violon1")
                   (violon2 #:notes "violon2")
                   (hautbois1 #:notes "hautbois1")
                   (hautbois2 #:notes "hautbois2")
                   (haute-contre)
                   (taille)
                   (basse)
                   (voix)
                   (basse-continue #:score "score-basse-continue"))
