\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois1 #:instrument "Violons")
                   (hautbois2 #:instrument "Violons")
                   (flute1 #:instrument "Violons")
                   (flute2 #:instrument "Violons")
                   (trompette)
                   (basse)
                   (timbales)
                   (voix))
