\piecePartSpecs #`((dessus #:score "score-dessus")
                   (trompette #:notes "dessus" #:tag-notes trompette)
                   (parties #:score-template "score-parties2")
                   (timbales #:notes "timbales")
                   (basse))
