\piecePartSpecs #`((dessus #:score "score-dessus")
                   (trompette #:notes "dessus" #:tag-notes trompette)
                   (haute-contre #:notes "parties" #:tag-notes haute-contre)
                   (taille #:notes "parties" #:tag-notes taille)
                   (timbales #:notes "timbales")
                   (basse))
