\piecePartSpecs #`((dessus #:score "score-dessus")
                   (haute-contre #:indent 0)
                   (taille #:indent 0)
                   (basse #:indent 0)
                   (basse-continue #:score-template "score-basse-continue-voix2" #:indent 0)
                   (silence #:score "score-silence" #:indent 0))
