\piecePartSpecs #`((violon1 #:notes "dessus")
                   (violon2 #:notes "dessus")
                   (haute-contre)
                   (taille)
                   (basse)
                   (voix)
                   (basse-continue #:score "score-basse-continue"))
