\piecePartSpecs #`((violon1 #:notes "violon1")
                   (violon2 #:score "score-violon2")
                   (flute1 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (flute2 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (hautbois1 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (hautbois2 #:notes "silence" #:score-template "score-silence" #:ragged #t)
                   (basse #:score "score-basse")
                   (voix)
                   (basse-continue #:score "score-basse"))
