\piecePartSpecs #`((violon1 #:notes "violon")
                   (violon2 #:notes "violon")
                   (flute1 #:notes "flute")
                   (flute2 #:notes "flute")
                   (hautbois1 #:notes "violon" #:instrument "Violons")
                   (hautbois2 #:notes "violon" #:instrument "Violons")
                   (basse))
