\piecePartSpecs #`((hautbois)
                   (haute-contre #:notes "haute-contre-taille")
                   (taille #:notes "haute-contre-taille")
                   (basson)
                   (basse))
