\piecePartSpecs
#`((oboe1)
   (oboe2)
   (clarinetto1)
   (clarinetto2)
   (fagotto1 #:notes "fagotti" #:clef "tenor")
   (fagotto2 #:notes "fagotti" #:clef "tenor")
   (violino1 #:notes "violino1")
   (violino2 #:notes "violino2")
   (alto)
   (basso #:instrument "Basso")
   (silence #:on-the-fly-markup , #{ \markup\tacet#24 #}))
