\piecePartSpecs #`((vocal)
                   (vocal-keyboard #:score "score")
                   (keyboard #:score-template "score-bassi" #:notes "bassi" #:clef "bass")
                   (bassi)
                   (silence #:score "score-silence"))