\piecePartSpecs #`((violons #:score "score-violons")
                   (flutes #:score "score-flutes")
                   (basse #:instrument "Les Basses")
                   (basse-continue #:score-template "score-basse-continue")
                   (silence #:score "score-silence"))
