\piecePartSpecs #'((violino1 #:notes "tutti")
                   (violino2 #:notes "tutti")
                   (oboe1 #:notes "tutti")
                   (oboe2 #:notes "tutti")
                   (violino3 #:notes "viola")
                   (viola)
                   (bassi #:score-template "score")
                   (keyboard)
                   (vocal-keyboard #:score-template "score-keyboard"))