\piecePartSpecs
#`((flauto1 #:notes "oboi" #:system-count 8)
   (flauto2 #:notes "oboi" #:system-count 8)
   (oboe1)
   (oboe2)
   (clarinetto1 #:notes "oboi" #:tag-notes oboe1)
   (clarinetto2 #:notes "oboi" #:tag-notes oboe2)
   (fagotto1)
   (fagotto2)
   (violino1)
   (violino2)
   (alto)
   (basso)
   (silence #:on-the-fly-markup , #{ \markup\tacet#83 #}))
