\piecePartSpecs #`((violon1)
                   (violon2)
                   (hautbois #:notes "trompettes-hautbois")
                   (trompette #:notes "trompettes-hautbois")
                   (haute-contre)
                   (taille)
                   (basse)
                   (timbales))
