\piecePartSpecs #`((violon1 #:notes "violon1")
                   (violon2 #:notes "violon2")
                   (hautbois1 #:notes "trompettes-hautbois")
                   (hautbois2 #:notes "trompettes-hautbois")
                   (trompette #:notes "trompettes-hautbois")
                   (haute-contre)
                   (taille)
                   (basse)
                   (timbales)
                   (basse-continue))
