\piecePartSpecs #`((hautbois1 #:tag-global autres)
                   (hautbois2 #:tag-global autres)
                   (violon1 #:tag-global autres)
                   (violon2 #:tag-global autres)
                   (haute-contre #:tag-global autres)
                   (taille #:tag-global autres)
                   (cor #:tag-global cor)
                   (basson #:tag-global autres)
                   (basse #:instrument "Basse continue")
                   (voix)
                   (basse-continue))
