\piecePartSpecs #`((basse-continue #:notes "basse-continue" #:score-template "score")
                   (voix)
                   (basse)
                   (quinte)
                   (taille)
                   (haute-contre)
                   (dessus2)
                   (dessus1))
