\piecePartSpecs #`((dessus #:score-template "score" #:notes "dessus")
                   (dessus-haute-contre)
                   (haute-contre #:notes "haute-contre")
                   (taille)
                   (basse))
