\piecePartSpecs #`((basse-continue #:score-template "score")
                   (timbales)
                   (trompette)
                   (basse)
                   (quinte)
                   (taille)
                   (haute-contre)
                   (dessus2)
                   (dessus1))
