\piecePartSpecs #`((violon1)
                   (violon2)
                   (voix)
                   (basson #:score "score-basson")
                   (basse #:instrument "Basse continue")
                   (basse-continue))
