\piecePartSpecs
#`((corno1 #:tag-global () #:instrument "Corno I en fa")
   (corno2 #:tag-global () #:instrument "Corno II en fa")
   (oboe1)
   (oboe2)
   (fagotto1 #:notes "fagotti")
   (fagotto2 #:notes "fagotti")
   (violino1 #:notes "violino1")
   (violino2 #:notes "violino2")
   (alto)
   (basso #:score "score-bassi")
   (silence #:on-the-fly-markup , #{ \markup\tacet#34 #}))
