\piecePartSpecs #`((dessus)
                   (haute-contre)
                   (taille)
                   (basse)
                   (basse-continue #:score-template "score-basse-continue2")
                   (silence #:score "score-silence" #:tag-notes silence))
