\piecePartSpecs #`((hautbois #:instrument "Hautbois seul")
                   (violon)
                   (basson #:instrument "Basson seul")
                   (basse #:instrument "Basse continue")
                   (basse-continue)
                   (voix))
