\piecePartSpecs #`((violon1 #:notes "violon")
                   (violon2 #:notes "violon")
                   (flute1 #:notes "flutes")
                   (flute2 #:notes "flutes")
                   (hautbois1 #:notes "violon" #:instrument "Violons")
                   (hautbois2 #:notes "violon" #:instrument "Violons")
                   (haute-contre #:notes "haute-contre")
                   (taille #:notes "taille")
                   (basse))
