\piecePartSpecs #`((violon1 #:notes "violon1")
                   (violon2 #:notes "violon2")
                   (flute1 #:notes "flute1")
                   (flute2 #:notes "flute2")
                   (hautbois1 #:notes "hautbois")
                   (hautbois2 #:notes "hautbois")
                   (voix)
                   (basse-continue))
