\piecePartSpecs #`((violon1)
                   (violon2 #:notes "violon2")
                   (flute1)
                   (flute2)
                   (hautbois1)
                   (hautbois2)
                   (voix)
                   (basse #:instrument "Basse continue")
                   (basse-continue))
