\piecePartSpecs #`((violon1)
                   (violon2)
                   (flute1)
                   (flute2)
                   (hautbois)
                   (voix)
                   (basse #:instrument "Basse continue")
                   (basse-continue))
