\piecePartSpecs #`((dessus)
                   (parties)
                   (basson #:instrument "Bassons" #:notes "basson")
                   (basse)
                   (silence #:on-the-fly-markup , #{ \markup\tacet #71 #}))
